Squashed commit of the following:
commit da77d99d6923708373b3b5f65483d6c31ff0dd66
Author: leuwen-lc <lcpro@etik.com>
Date:   Mon Dec 8 21:33:41 2025 +0100

    docs : refonte de la doc SECURITE_WEB.md

commit 46f6e371e746da65aec1712a1be868d9cb782dd6
Author: leuwen-lc <lcpro@etik.com>
Date:   Sun Dec 7 22:25:11 2025 +0100

    qual : factorisation code de test SecurityConfigCSP + passage à Spring Boot 3.5.8 plutot que 3.5.7

commit 6cc3b28a76c2a0e4a58e840be7dfa871d91d7abe
Author: leuwen-lc <lcpro@etik.com>
Date:   Sun Dec 7 22:11:26 2025 +0100

    fix : nouveau changement pour charger les données h2 de manière fiable avant les tests d'intégration

commit fc583f535b2bd9de9c13e1a59e9cbf33d1950a83
Author: leuwen-lc <lcpro@etik.com>
Date:   Sun Dec 7 21:54:49 2025 +0100

    fix : mode de chargement des données initiales dans H2 pour les tests d'intégration, rename de SecurityConfigTest en SecurityConfigIT

commit 49063110758592cb5af5baca1b301cf17dbaf21a
Author: leuwen-lc <lcpro@etik.com>
Date:   Sun Dec 7 21:24:00 2025 +0100

    fix : corrections ajout de token CSRF aux requètes POST en test d'intégration  nécessaire suite à configuration de TestSecurityConfig.

commit 409b07545ae3415cd6c4474ab5c14888bd0adbe4
Author: leuwen-lc <lcpro@etik.com>
Date:   Sun Dec 7 10:14:03 2025 +0100

    qual : ajout de tests unitaires et d'intégration sur la partie Spring Security pour satisfaire le quality gate SonarQube

commit 0373ea7f8a77f228774cd812843bcebeecab47cd
Author: leuwen-lc <lcpro@etik.com>
Date:   Sat Dec 6 14:55:04 2025 +0100

    fix : problème de syntaxe set +x dans le jenkins file

commit 635344a758c82a6a795fd35e7b2f6ec780630705
Author: leuwen-lc <lcpro@etik.com>
Date:   Sat Dec 6 12:13:53 2025 +0100

    fix : - résolution de vulnérabilités apparaissant dans les rapports zap (ajout de CSP dans spring Boot et keycloak), suppression de X-Frame-Options dupliqué avec Nginx
    - externalisation des css et js dans error.html et index.html pour pouvoir appliquer les CSP de manière plus stricte
    - Modification du jenkinsfile pour suppression de l'affichage des secrets dans les logs.

commit b5b5e94a18fe31bbdb3a85143b757cb70c3ac002
Author: leuwen-lc <lcpro@etik.com>
Date:   Sat Dec 6 09:38:28 2025 +0100

    fix: corriger le chemin de chargement de la bibliothèque rhDemoLib.groovy

    Le repository parent contient rhDemo/ comme sous-répertoire.
    Jenkins checkout le repo parent, donc le chemin doit être
    'rhDemo/vars/rhDemoLib.groovy' et non 'vars/rhDemoLib.groovy'.

    Cette correction résout l'erreur:
    NoSuchFileException: /var/jenkins_home/workspace/rhdemo-pipeline/vars/rhDemoLib.groovy

commit 1f2ad808d01f1982609e6df7d0e5a547941bfdc2
Author: leuwen-lc <lcpro@etik.com>
Date:   Sat Dec 6 09:18:02 2025 +0100

    refact : rendre plus maintenanble le Jenkinsfile
    - Factorisation de code
    - Création d'une shared lin Groovy
    - Création de fichiers de code séparé pour les parties script sh